swagger: "2.0"
info:
  title: 后台管理系统API文档
  description: 后台管理系统接口文档
  version: 0.0.1

host: dubhe-app-admin
basePath: /api
schemes:
  - http

paths:
  /Notices:
    get:
      summary: 获取通知列表
      produces:
        - application/json
      parameters:
        - in: query
          name: companyId
          type: integer
          minimum: 0
          required: true
          description: 公司id.
        - in: query
          name: offSet
          type: integer
          minimum: 0
          required: true
          description: 从第几条开始显示.
        - in: query
          name: limit
          type: integer
          minimum: 0
          required: true
          description: 每页显示条数.
        - in: query
          name: partition
          type: integer
          minimum: 0
          required: false
          description: 所属模块.
        - in: query
          name: noticeType
          type: integer
          minimum: 0
          required: false
          description: 所属类型
        - in: query
          name: updated_at
          type: string
          format: date-time
          required: false
          description: 更新时间.
      responses:
        200:
          description: OK
          headers:
            total:
              type: integer
              minimum: 0
              description: 数据总数
          schema:
            type: array
            items:
              $ref: '#/definitions/Notice'
    post:
      summary: 增加一个新通知
      produces:
        - application/json
      #请求参数
      parameters:
          #参数key
        - name: partition
          in: formData
          description: 所属模块id
          required: true
          type: integer
          minimum: 0
        - name: noticeTypeId
          in: formData
          description: 所属类型id
          required: true
          type: integer
          minimum: 0
        - name: title
          in: formData
          type: string
          description: 通知标题
          required: true
        - name: abstract
          in: formData
          type: string
          description: 摘要
          required: true
        - name: imgId
          in: formData
          type: string
          description: 图片id
          required: true
        - name: substance
          in: formData
          type: string
          description: 具体内容
          required: true
        - name: status
          in: formData
          type: integer
          minimum: 0
          description: 紧急程度（默认为0）
          required: true
        - name: sys_adder
          in: formData
          type: integer
          minimum: 0
          description: 添加人id
          required: true
      responses:
        200:
          description: OK
          schema:
             #值类型
              type: object
              $ref: '#/definitions/Notice'
  /Notice/{noticeId}:
    get:
      summary: 根据id查询通知
      produces:
        - application/json
      parameters:
        #上面接口中定义了{id}，则参数列表中必须包含参数id,并且请求类型为path
        - name: noticeId
          in: path
          description: 要查询的通知的id,它是唯一标识
          required: true
          type: integer
          minimum: 0
      responses:
        200:
          description: OK
          schema:
              $ref: '#/definitions/Notice'
    patch:
      summary: 修改通知
      produces:
        - application/json
      #请求参数
      parameters:
          #参数key
        - name: noticeId
          in: path
          description: 所选通知id
          required: true
          type: integer
          minimum: 0
        - name: partition
          in: formData
          description: 所属模块id
          required: false
          type: integer
          minimum: 0
        - name: noticeTypeId
          in: formData
          description: 所属类型id
          required: false
          type: integer
          minimum: 0
        - name: title
          in: formData
          type: string
          description: 通知标题
          required: false
        - name: abstract
          in: formData
          type: string
          description: 摘要
          required: false
        - name: imgId
          in: formData
          type: string
          description: 图片id
          required: false
        - name: substance
          in: formData
          type: string
          description: 具体内容
          required: false
        - name: status
          in: formData
          type: integer
          minimum: 0
          description: 紧急程度
          required: false
        - name: sys_updator
          in: formData
          type: integer
          description: 修改人id
          required: true
      responses:
        200:
          description: OK
          schema:
             #值类型
              type: object
              $ref: '#/definitions/Notice'
    delete:
      summary: 删除通知
      parameters:
        - name: noticeId
          in: path
          type: integer
          minimum: 0
          required: true
        - name: userId
          in: query
          type: integer
          minimum: 0
          required: true
      responses:
        '204':
          description: The resource was deleted successfully.
  /NoticeType:
    get:
      summary: 获取通知类型列表
      produces:
        - application/json
      parameters:
        - in: query
          name: companyId
          type: integer
          minimum: 0
          required: true
          description: 公司id.
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/NoticeType'
  /NoticesHistory:
    get:
      summary: 获取发送通知历史列表
      produces:
        - application/json
      parameters:
        - in: query
          name: companyId
          type: integer
          minimum: 0
          required: true
          description: 公司id.
        - in: query
          name: offset
          type: integer
          minimum: 0
          required: true
          description: 从第几条开始显示.
        - in: query
          name: limit
          type: integer
          minimum: 0
          required: true
          description: 每页显示条数.
        - in: query
          name: partition
          type: integer
          minimum: 0
          required: false
          description: 所属模块.
        - in: query
          name: noticeType
          type: integer
          minimum: 0
          required: false
          description: 所属类型
        - in: query
          name: create_at
          type: string
          format: date-time
          required: false
          description: 发送时间.
        - in: query
          name: departmentId
          type: integer
          minimum: 0
          required: false
          description: 发送部门.
      responses:
        200:
          description: OK
          headers:
            total:
              type: integer
              minimum: 0
              description: 数据总数
          schema:
            type: array
            items:
              $ref: '#/definitions/NoticeHistory'
    post:
      summary: 发送接口
      produces:
        - application/json
      #请求参数
      parameters:
          #参数key
        - name: noticeId
          in: formData
          description: 通知id
          required: true
          type: integer
          minimum: 0
        - name: department
          in: formData
          description: 发送部门id数组
          required: true
          type: string
          minimum: 0
        - name: companyId
          in: formData
          type: integer
          minimum: 0
          description: 公司id
          required: true
        - name: sys_adder
          in: formData
          type: integer
          minimum: 0
          description: 添加人id
          required: true
      responses:
        200:
          description: notices push successfully
  /NoticeHistory/{noticeId}:
    get:
      summary: 根据id查询发送通知详情
      produces:
        - application/json
      parameters:
        - name: noticeId
          in: path
          description: 要查询的通知的id,它是唯一标识
          required: true
          type: integer
          minimum: 0
      responses:
        200:
          description: OK
          schema:
              $ref: '#/definitions/NoticeHistory'
  /Department/{companyId}:
    get:
      summary: 查询公司部门信息
      produces:
        - application/json
      parameters:
        - name: companyId
          in: path
          description: 公司id
          required: true
          type: integer
          minimum: 0
      responses:
        200:
          description: OK
          schema:
              $ref: '#/definitions/Department'
              
  /api/OSSConfig/Notice:
    get:
      summary: 通知部分图片上传接口
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
              $ref: '#/definitions/UploadPathAndSignature'

definitions:
  Notice:
    type: object
    properties:
      id:
        type: integer
        minimum: 0
        description: 主键id
      noticeTypeId:
        type: integer
        minimum: 0
        description: 通知类型id
      title:
        type: string
        description: 通知标题
      contents: 
        type: string
        description: 通知内容
      status: 
        type: integer
        minimum: 0
        description: 紧急程度 
      sys_addTime: 
        type: string
        format: date-time
        description: 创建时间
      sys_updateTime: 
        type: string
        format: date-time
        description: 更新时间
      sys_adder: 
        type: integer
        minimum: 0
        description: 创建人id
      sys_updator: 
        type: integer
        minimum: 0
        description: 创建人id
      noticeType: 
        type: object
        properties: 
          partition:
            type: integer
            minimum: 0
            description: 所属模块
          name: 
            type: string
            description: 类型名称
      imgId:
        type: string
        description: 图片id
  NoticeType:
    type: object
    properties: 
      partition:
        type: integer
        minimum: 0
        description: 通知模块
      noticeType:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
              minimum: 0
              description: 通知类型id
            name:
              type: string
              description: 通知类型名称
        description: 通知类型
  NoticeHistory:
    type: object
    properties:
      sys_addTime: 
        type: string
        format: date-time
        description: 创建时间
      sys_updateTime: 
        type: string
        format: date-time
        description: 更新时间
      sys_adder: 
        type: integer
        minimum: 0
        description: 创建人id
      sys_updator: 
        type: integer
        minimum: 0
        description: 创建人id
      notice: 
        type: object
        properties: 
          id:
            type: integer
            minimum: 0
            description: 主键id
          noticeTypeId:
            type: integer
            minimum: 0
            description: 通知类型id
          title:
            type: string
            description: 通知标题
          contents: 
            type: string
            description: 通知内容
        
      department: 
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                minimum: 0
                description: 通知类型id
              name:
                type: string
                description: 通知类型名称
          description: 发送部门
  Department:
    type: array
    items: 
      type: object
      properties:
        id: 
          type: integer
          minimum: 0
          description: 主键id
        name:
          type: string
          description: 部门名称
  UploadPathAndSignature:
    type: object
    properties:
      accessid: 
        type: string
        description: 用户请求的accessid
      host:
        type: string
        description: 用户要往哪个域名发送上传请求
      policy:
        type: string
        description: 用户表单上传的策略（Policy），是经过base64编码过的字符串
      signature: 
         type: string
         description: 签名
      expire: 
        type: string
        description: 上传策略失效时间